Subscribe
MaximKarlov/FoodSTA_UTF-8 pull request #23
Opened 2022-10-31 21:52 UTC by Hnatiak

2022-10-31 23:19 UTC, Hnatiak commented
Я хотів зробити плавний перехід, бо дуже великі відриви

пн, 31 жовт. 2022 р. о 23:02 Illia ***@***.***> пише:

> ***@***.**** commented on this pull request.
>
> що за медіа-копі?
> що за медіа (мін віз 541)
> що за медіа (макс-відз 540)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MaximKarlov/FoodSTA_UTF-8/pull/23#pullrequestreview-1162615342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN3JERZKREGUALXEHYTFXA3WGA6XXANCNFSM6AAAAAARTQBFLM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-31 23:23 UTC, Hnatiak commented
Я поняття не маю що то за медіа копі, і як вона створилася, я брав усе від
_media.scss


пн, 31 жовт. 2022 р. о 23:02 Illia ***@***.***> пише:

> ***@***.**** commented on this pull request.
>
> що за медіа-копі?
> що за медіа (мін віз 541)
> що за медіа (макс-відз 540)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MaximKarlov/FoodSTA_UTF-8/pull/23#pullrequestreview-1162615342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN3JERZKREGUALXEHYTFXA3WGA6XXANCNFSM6AAAAAARTQBFLM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-01 09:54 UTC, MaximKarlov requested changes
У тебе є конфлікт... Будь ласка поправ...

2022-11-01 10:00 UTC, MaximKarlov approved these changes

2022-11-01 10:00 UTC, merged